import type { Meeting, Person, VisionRecognitionPerson, VisionRecognitionResult, VenueType } from "@/features/seating/types";
import { createId } from "@/lib/utils";
const normalize = (value: string) => value.trim().toLowerCase().replace(/\s+/g, "");
const priorityOrFallback = (priority: number | undefined, fallback: number) => Number.isFinite(priority) && (priority ?? 0) > 0 ? Number(priority) : fallback;
const resolveRegionId = (meeting: Meeting, regionName?: string) => regionName ? meeting.regions.find((region) => normalize(region.name) === normalize(regionName))?.id : undefined;
const resolveLineId = (meeting: Meeting, lineName?: string) => lineName ? meeting.lines.find((line) => normalize(line.name) === normalize(lineName))?.id : undefined;
function createVenueConfig(venueType: VenueType, rostrumCapacity: number): Meeting["venueConfig"] { if (venueType === "large") return { venueType: "large", rostrumCapacity, audienceRows: 15, audienceBlocks: [5, 7, 5], seatOrderMode: "left-honor", groupMode: "none", lineZones: [] }; if (venueType === "u_shape") return { venueType: "u_shape", rostrumCapacity, leftSeats: 8, rightSeats: 8, groupMode: "none" }; return { venueType: "hollow_square", rostrumCapacity, leftSeats: 6, rightSeats: 6, bottomSeats: 8, innerWidth: 4, innerHeight: 2, groupMode: "none" }; }
function convertPeople(meeting: Meeting, people: VisionRecognitionPerson[], fallbackArea: "rostrum" | "audience") { return people.map<Person>((person, index) => ({ id: createId("person"), name: person.name.trim(), title: person.title.trim(), priority: priorityOrFallback(person.priority, index + 1), status: "normal", areaType: person.areaType ?? fallbackArea, regionId: resolveRegionId(meeting, person.regionName), lineId: resolveLineId(meeting, person.lineName) })); }
export function applyVisionResultToMeeting(meeting: Meeting, result: VisionRecognitionResult, mode: "replace" | "merge") { const rostrumPeople = convertPeople(meeting, result.rostrumPeople, "rostrum"); const audiencePeople = convertPeople(meeting, result.audiencePeople, "audience"); const recognized = [...rostrumPeople, ...audiencePeople]; const nextVenueConfig = result.venueType ? createVenueConfig(result.venueType, meeting.venueConfig.rostrumCapacity) : meeting.venueConfig; if (mode === "replace") return { ...meeting, venueConfig: nextVenueConfig, people: recognized }; const mergedByName = new Map(meeting.people.map((person) => [normalize(person.name), person])); for (const person of recognized) mergedByName.set(normalize(person.name), person); return { ...meeting, venueConfig: nextVenueConfig, people: [...mergedByName.values()] }; }
export function safeParseVisionResult(raw: string): VisionRecognitionResult | null { try { const parsed = JSON.parse(raw) as VisionRecognitionResult; if (!parsed || !Array.isArray(parsed.rostrumPeople) || !Array.isArray(parsed.audiencePeople)) return null; return { venueType: parsed.venueType, confidence: parsed.confidence, summary: parsed.summary ?? "", rostrumPeople: parsed.rostrumPeople, audiencePeople: parsed.audiencePeople }; } catch { return null; } }
