import * as XLSX from "xlsx";
import type { AreaType, ImportOptions, ImportResult, Meeting, Person, PersonStatus } from "@/features/seating/types";
import { createId } from "@/lib/utils";
const HEADER_KEYWORDS = { priority: ["优先级", "序号", "编号", "顺序", "排名", "priority", "no", "number"], name: ["姓名", "名字", "人员", "参会人", "name"], title: ["职务", "职位", "职称", "职级", "岗位", "title", "position"], region: ["区域", "企业", "单位", "组织", "region", "部门"], line: ["条线", "业务线", "线条", "department", "line"], area: ["归属", "区域类型", "座区", "席位区", "area", "seatarea"], status: ["状态", "出席状态", "attendance", "status"] } as const;
const ROSTRUM_KEYWORDS = ["主席台", "主席", "台上", "rostrum", "stage"];
const AUDIENCE_KEYWORDS = ["台下", "观众", "会场", "audience", "floor"];
const ABSENT_KEYWORDS = ["缺席", "请假", "未到", "absent"];
const NORMAL_KEYWORDS = ["正常", "出席", "到场", "normal", "present"];
const normalize = (value: unknown) => String(value ?? "").trim().toLowerCase().replace(/\s+/g, "");
const matchHeader = (header: string, candidates: readonly string[]) => candidates.some((candidate) => header === normalize(candidate) || header.includes(normalize(candidate)) || normalize(candidate).includes(header));
function parseAreaType(value: unknown, fallback: AreaType) { const normalized = normalize(value); if (!normalized) return fallback; if (ROSTRUM_KEYWORDS.some((item) => normalized.includes(normalize(item)))) return "rostrum"; if (AUDIENCE_KEYWORDS.some((item) => normalized.includes(normalize(item)))) return "audience"; return fallback; }
function parseStatus(value: unknown): PersonStatus { const normalized = normalize(value); if (!normalized) return "normal"; if (ABSENT_KEYWORDS.some((item) => normalized.includes(normalize(item)))) return "absent"; if (NORMAL_KEYWORDS.some((item) => normalized.includes(normalize(item)))) return "normal"; return "normal"; }
function buildIndexes(headerRow: unknown[]) { const normalizedHeaders = headerRow.map(normalize); return { priority: normalizedHeaders.findIndex((header) => matchHeader(header, HEADER_KEYWORDS.priority)), name: normalizedHeaders.findIndex((header) => matchHeader(header, HEADER_KEYWORDS.name)), title: normalizedHeaders.findIndex((header) => matchHeader(header, HEADER_KEYWORDS.title)), region: normalizedHeaders.findIndex((header) => matchHeader(header, HEADER_KEYWORDS.region)), line: normalizedHeaders.findIndex((header) => matchHeader(header, HEADER_KEYWORDS.line)), area: normalizedHeaders.findIndex((header) => matchHeader(header, HEADER_KEYWORDS.area)), status: normalizedHeaders.findIndex((header) => matchHeader(header, HEADER_KEYWORDS.status)) }; }
function dedupeImportedPeople(people: Person[], existingPeople: Person[], duplicateHandling: ImportOptions["duplicateHandling"], warnings: Set<string>) { if (duplicateHandling === "keep") return people; const existingNameMap = new Map(existingPeople.map((person) => [normalize(person.name), person])); return people.filter((person) => { const existing = existingNameMap.get(normalize(person.name)); if (!existing) return true; if (duplicateHandling === "skip") { warnings.add(`姓名“${person.name}”与现有人员重名，已跳过。`); return false; } warnings.add(`姓名“${person.name}”与现有人员重名，导入后将覆盖现有人员。`); return true; }); }
function applyOverwrite(people: Person[], existingPeople: Person[], duplicateHandling: ImportOptions["duplicateHandling"]) { if (duplicateHandling !== "overwrite") return { imported: people, remaining: existingPeople }; const importedNames = new Set(people.map((person) => normalize(person.name))); return { imported: people, remaining: existingPeople.filter((person) => !importedNames.has(normalize(person.name))) }; }
export async function parsePeopleExcel(file: File, meeting: Meeting, options: ImportOptions): Promise<ImportResult & { remainingPeople: Person[] }> { const buffer = await file.arrayBuffer(); const workbook = XLSX.read(buffer, { type: "array" }); const sheet = workbook.Sheets[workbook.SheetNames[0]]; if (!sheet) return { people: [], remainingPeople: options.existingPeople, warnings: ["未读取到工作表内容。"] }; const rows = XLSX.utils.sheet_to_json<(string | number | undefined)[]>(sheet, { header: 1, raw: false }); const [headerRow, ...dataRows] = rows; if (!headerRow) return { people: [], remainingPeople: options.existingPeople, warnings: ["表格缺少表头。"] }; const indexes = buildIndexes(headerRow); if (indexes.name === -1) return { people: [], remainingPeople: options.existingPeople, warnings: ["未识别到姓名列，请检查表头。"] }; const regionByName = new Map(meeting.regions.map((region) => [normalize(region.name), region.id])); const lineByName = new Map(meeting.lines.map((line) => [normalize(line.name), line.id])); const warnings = new Set<string>(); const importedPeople = dataRows.map((row, index): Person | null => { const name = String(row[indexes.name] ?? "").trim(); if (!name) { warnings.add(`第 ${index + 2} 行缺少姓名，已跳过。`); return null; } const title = indexes.title >= 0 ? String(row[indexes.title] ?? "").trim() : ""; const priorityRaw = indexes.priority >= 0 ? row[indexes.priority] : undefined; const priorityValue = Number.parseInt(String(priorityRaw ?? ""), 10); const regionName = indexes.region >= 0 ? String(row[indexes.region] ?? "").trim() : ""; const lineName = indexes.line >= 0 ? String(row[indexes.line] ?? "").trim() : ""; const areaType = indexes.area >= 0 ? parseAreaType(row[indexes.area], options.defaultAreaType) : options.defaultAreaType; const status = indexes.status >= 0 ? parseStatus(row[indexes.status]) : "normal"; const regionId = regionByName.get(normalize(regionName)); const lineId = lineByName.get(normalize(lineName)); if (regionName && !regionId) warnings.add(`区域“${regionName}”未匹配，已保留为空。`); if (lineName && !lineId) warnings.add(`条线“${lineName}”未匹配，已保留为空。`); return { id: createId("person"), name, title, priority: Number.isFinite(priorityValue) && priorityValue > 0 ? priorityValue : index + 1, status, areaType, regionId, lineId }; }).filter((person): person is Person => person !== null); const dedupedPeople = dedupeImportedPeople(importedPeople, options.existingPeople, options.duplicateHandling, warnings); const { imported, remaining } = applyOverwrite(dedupedPeople, options.existingPeople, options.duplicateHandling); return { people: imported, remainingPeople: remaining, warnings: [...warnings] }; }
