"use client";
import type { ReactNode } from "react";
import { AlertCircle, CheckCircle2, HelpCircle, Info, LoaderCircle, Sparkles, TriangleAlert } from "lucide-react";
import { cn } from "@/lib/utils";
export type StatusTone = "success" | "warning" | "error" | "info";
export function EmptyState({ title, description, action, icon }: { title: string; description: string; action?: ReactNode; icon?: ReactNode }) { return <div className="rounded-[28px] border border-dashed border-slate-300 bg-slate-50 px-6 py-10 text-center"><div className="mx-auto flex size-12 items-center justify-center rounded-full bg-white text-slate-500 shadow-sm">{icon ?? <HelpCircle className="size-5" />}</div><h3 className="mt-4 text-base font-semibold text-slate-900">{title}</h3><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-slate-500">{description}</p>{action ? <div className="mt-5">{action}</div> : null}</div>; }
export function StatusBanner({ tone, title, description }: { tone: StatusTone; title: string; description?: string }) { const appearance = { success: { wrap: "border-emerald-200 bg-emerald-50 text-emerald-900", icon: <CheckCircle2 className="mt-0.5 size-4 shrink-0" /> }, warning: { wrap: "border-amber-200 bg-amber-50 text-amber-900", icon: <TriangleAlert className="mt-0.5 size-4 shrink-0" /> }, error: { wrap: "border-rose-200 bg-rose-50 text-rose-900", icon: <AlertCircle className="mt-0.5 size-4 shrink-0" /> }, info: { wrap: "border-sky-200 bg-sky-50 text-sky-900", icon: <Info className="mt-0.5 size-4 shrink-0" /> } }[tone]; return <div className={cn("rounded-2xl border px-4 py-3", appearance.wrap)}><div className="flex gap-3">{appearance.icon}<div><div className="text-sm font-medium">{title}</div>{description ? <div className="mt-1 text-sm opacity-90">{description}</div> : null}</div></div></div>; }
export function ConfirmDialog({ open, title, description, confirmLabel, cancelLabel, destructive, onConfirm, onCancel }: { open: boolean; title: string; description: string; confirmLabel?: string; cancelLabel?: string; destructive?: boolean; onConfirm: () => void; onCancel: () => void }) { if (!open) return null; return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/35 px-4 py-8 backdrop-blur-sm"><div className="w-full max-w-md rounded-[28px] border border-white/70 bg-white p-6 shadow-2xl shadow-slate-900/20"><h3 className="text-lg font-semibold text-slate-950">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{description}</p><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onCancel} className="rounded-full border border-slate-300 px-4 py-2 text-sm text-slate-700 transition hover:bg-slate-50">{cancelLabel ?? "取消"}</button><button type="button" onClick={onConfirm} className={cn("rounded-full px-4 py-2 text-sm font-medium text-white transition", destructive ? "bg-rose-600 hover:bg-rose-500" : "bg-slate-950 hover:bg-slate-800")}>{confirmLabel ?? "确认"}</button></div></div></div>; }
export function LoadingPill({ text }: { text: string }) { return <span className="inline-flex items-center gap-2 rounded-full bg-slate-100 px-3 py-1.5 text-xs font-medium text-slate-700"><LoaderCircle className="size-3.5 animate-spin" />{text}</span>; }
export function AiBadge() { return <span className="inline-flex items-center gap-1 rounded-full bg-sky-100 px-2.5 py-1 text-xs font-medium text-sky-900"><Sparkles className="size-3.5" />AI 识图</span>; }
